<a href="https://colab.research.google.com/github/Aditya089081/DATA-SCIENCE-TOOLBOX-PYTHON-PROGRAMMING/blob/main/Numpy_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
n1 = np.array([10,20,30,40,50])
print(n1)

[10 20 30 40 50]


In [ ]:
import numpy as np
n2 = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(n2)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [ ]:
n3 = np.zeros((3,3),dtype = int)
print(n3)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [16]:
n4 = np.full((3,3),5)
print(n4)
n5 = np.arange(10,20,2)
print(n5)

[[5 5 5]
 [5 5 5]
 [5 5 5]]
[10 12 14 16 18]


In [23]:
n6 = np.array(np.random.randint(1,200,4))
print(n6.shape)
n6.shape = (2,2)
print(n6)

(4,)
[[171 174]
 [166 141]]


In [26]:
                        # vstack
                        # -- join array vertically

n7 = np.array([10,20,30,40,50])
n8 = np.array([60,70,80,90,100])
n9 = np.vstack((n7,n8))
print(n9)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [31]:
                          #  hstack
                          # join array at horizontally
n10 = np.hstack((n7,n8,n1))
print(n10)


[ 10  20  30  40  50  60  70  80  90 100  10  20  30  40  50]


In [34]:
                            # column_stack
                            #  -- ek array ek colun ma
# n11 = np.column_stack((n7,n8))
n11 = np.column_stack((n7,n8,n1))
print(n11)

[[ 10  60  10]
 [ 20  70  20]
 [ 30  80  30]
 [ 40  90  40]
 [ 50 100  50]]


In [40]:
n12 = np.intersect1d(n7,n8)
print(n12)
n13 = np.setdiff1d(n7,n8)
print(n13)
print(np.sum([n7,n8]))
# print(np.sum([n7,n8],axis = 0))
n7 = n7+1
print(n7)

[]
[11 21 31 41 51]
555
[12 22 32 42 52]


In [47]:
n14 = np.mean(n7)
print(n14)
n15 = np.median(n7)
print(n15)
n16 = np.std(n7)
print(n16)
n17 = np.save("my_save",n7)
n18 = np.load("my_save.npy")
print(n18)

32.0
32.0
14.142135623730951
[12 22 32 42 52]
