<a href="https://colab.research.google.com/github/Aditya089081/DATA-SCIENCE-TOOLBOX-PYTHON-PROGRAMMING/blob/main/Numpy_practice(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a1 = np.array([1,2,3,4,5,6,7])
a2 = np.array([3,4,5,6,7,8,9])
a3 = np.ones((1,5));
print(a3)
a4 = np.full((1,5),5)
print(a4)


[[1. 1. 1. 1. 1.]]
[[5 5 5 5 5]]


In [13]:
a5 = np.arange(10,20,2)
print(a5)
a6 = np.random.randint(1,100,(2,3))
a6.shape = (2,3)
print(a6)


[10 12 14 16 18]
[[13 52  5]
 [ 9 39 55]]


In [16]:
a7 = np.vstack((a1,a2))
print(a7)
a8 = np.hstack((a1,a2))
print(a8)

[[1 2 3 4 5 6 7]
 [3 4 5 6 7 8 9]]
[1 2 3 4 5 6 7 3 4 5 6 7 8 9]


In [21]:
a9 = np.column_stack((a1,a2))
print(a9)

[[1 3]
 [2 4]
 [3 5]
 [4 6]
 [5 7]
 [6 8]
 [7 9]]


In [37]:
a11 = np.intersect1d(a1,a2)
print(a11)
a22 = np.setdiff1d(a1,a2)
print(a22)
a33 = np.sum((a1))
print(a33)
a44 = np.sum((a1,a2))
print(a44)
# a55 = np.sum((a1,a2),axis=0)
a66 = a1+a2
print(a66)


[3 4 5 6 7]
[1 2]
28
70
[ 4  6  8 10 12 14 16]


In [42]:
# a1 = a1+1
# a1 = a1-1
print(a1)


[1 2 3 4 5 6 7]


In [48]:
a77 = np.mean(a1)
print(a77)
a88 = np.median(a1)
print(a88)
a99 = np.std(a1)
print(a99)

4.0
4.0
2.0


In [50]:
np.save('name',a1)
a111 = np.load('name.npy')
print(a111)

[1 2 3 4 5 6 7]
