<a href="https://colab.research.google.com/github/Aditya089081/DATA-SCIENCE-TOOLBOX-PYTHON-PROGRAMMING/blob/main/week1_NPTEL_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
data = pd.read_excel("/content/IRIS.xlsx")
data.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [3]:
n1 = data['sepal_length']
n2 = data['petal_length']
print(n1)
print(n2)

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64
0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ... 
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: petal_length, Length: 150, dtype: float64


In [5]:
n11 = np.zeros((5,5))
n22 = np.full((5,5),5)
n33 = np.arange(100,200,10)
print(n11)
print(n22)
print(n33)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
[100 110 120 130 140 150 160 170 180 190]


In [11]:
n44 = np.random.randint(100,200,10)
print(n44)
n44 = np.sort(n44)
print(n44)
n44.shape
n445 = n44.reshape(2,5)
print(n445)

[119 167 113 110 112 137 181 107 112 158]
[107 110 112 112 113 119 137 158 167 181]
[[107 110 112 112 113]
 [119 137 158 167 181]]


In [17]:
n12 = np.vstack((n1,n2))
print(n12)
n21 = np.hstack((n1,n2))
print(n21)
n1122 = np.column_stack((n1,n2))
print(n1122)


[[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
  5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
  5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
  6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
  6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
  5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
  6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
  6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
  6.7 6.7 6.3 6.5 6.2 5.9]
 [1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 1.5 1.6 1.4 1.1 1.2 1.5 1.3 1.4
  1.7 1.5 1.7 1.5 1.  1.7 1.9 1.6 1.6 1.5 1.4 1.6 1.6 1.5 1.5 1.4 1.5 1.2
  1.3 1.5 1.3 1.5 1.3 1.3 1.3 1.6 1.9 1.4 1.6 1.4 1.5 1.4 4.7 4.5 4.9 4.
  4.6 4.5 4.7 3.3 4.6 3.9 3.5 4.2 4.  4.7 3.6 4.4 4.5 4.1 4.5 3.9 4.8 4.
  4.9 4.7 4.3 4.4 4.8 5.  4.5 3.5 3.8 3.7 3.9 5.1 4.5 4.5 4.7 4.4 4.1 4.
  4.4 4.6 4.  3

In [20]:
n122 = np.intersect1d(n1,n2)
print(n122)
n133 = np.setdiff1d(n1,n2)
print(n133)


[4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.
 6.1 6.3 6.4 6.6 6.7 6.9]
[6.2 6.5 6.8 7.  7.1 7.2 7.3 7.4 7.6 7.7 7.9]


In [28]:
n3 = np.sum([n1,n2])
print(n3)
print(np.sum(n1,axis=0))
print(np.sum([n1,n2],axis = 1))
n1 = n1+n2
print(n1)


2004.1000000000001
1440.3
[1440.3  563.8]
0       7.9
1       7.7
2       7.3
3       7.6
4       7.8
       ... 
145    17.1
146    16.3
147    16.9
148    17.0
149    16.1
Length: 150, dtype: float64


In [29]:
print(n1.mean())
print(n1.median())
print(n1.std())

13.360666666666665
14.350000000000001
4.270028160582786
